### ISSUE TITLE
[Bug]: Blog posts filtered for the Malaysia CO show up as a blank page. 

### ISSUE THREAD

**Issue by albertocottica** [UNDP-Accelerator-Labs/blog-scraper#18]
### Issue description

![image](https://github.com/UNDP-Accelerator-Labs/blog-scraper/assets/1976806/eefc0e94-0681-4c86-9cc5-b673cda2abb3)

### Where did this happen?

https://www.sdg-innovation-commons.org/en/browse/blog/preview?source=blog&search=&country=Malaysia%2C+Singapore+%26+Brunei+Darussalam

Notice that this does not always happen. For example

https://www.sdg-innovation-commons.org/en/browse/blog/preview?source=blog&search=&country=Libya

So likely some characters like `,` incorrectly rendered in the URL.

It's the blog platform, not supported by the drop-down menu.

### What do you expect?

To see the 51 items that the filter announces. 

### Platform

Global

### What browsers are you seeing the problem on?

Firefox

### Add any other relevant details

Relevant info

**Comment by this-pama** [comment]
Please use the [insight](https://insights.sdg-innovation-commons.org/browse) for article search going forward. The global platform will be redesign and repurpose in the future. Thanks!
