### ISSUE TITLE
[ENHANCEMENT]: enable sorting by date

### ISSUE THREAD

**Issue by albertocottica** [UNDP-Accelerator-Labs/blog-scraper#21]
### What areas do you propose needs enhancement or improvement?

Enable sorting by date

### Where is the current state/behavior?

It does not sort by date

### How will the proposed enhancement improve the system?

self-evident

**Comment by this-pama** [comment]
The return articles are now sorted by date. This should do for now. Future fuctionality could be to add date range filter for user to search by date range. Closing this for now.
